# Generated by Django 6.1.1 on 2026-10-01 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, verbose_name="token hash"),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="user agent"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="first IP address"),
                ),
                (
                    "last_ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="last IP address"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="first seen"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="last seen"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "trusted device",
                "verbose_name_plural": "trusted devices",
                "ordering": ["-last_used_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "token_hash"),
                        name="trusted_device_unique_user_token",
                    )
                ],
            },
        ),
    ]
