# Generated by Django 6.1.1 on 2026-10-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allauth_trusted_devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trusteddevice",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="removed"),
        ),
    ]
